# Generated by Django 5.0.2 on 2024-03-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, help_text='If you dont wanna give a discount, put this field free.', null=True),
        ),
    ]
