# Generated by Django 5.0.2 on 2024-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
