# Generated by Django 4.2.3 on 2023-08-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_comment_user_email_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_email',
        ),
    ]
