# Generated by Django 5.0.2 on 2024-05-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_productprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
