# Generated by Django 5.0.2 on 2024-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_ip_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='product_app.ip'),
        ),
    ]
