# Generated by Django 5.0.4 on 2024-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='value',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
