# Generated by Django 4.2.3 on 2023-08-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
