# Generated by Django 5.0.2 on 2024-04-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('refund', 'refund')], default=(), editable=False, max_length=20),
        ),
    ]
