# Generated by Django 5.0.2 on 2024-05-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
