# Generated by Django 5.0.2 on 2024-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('refund', 'refund')], default='unpaid', max_length=20),
        ),
    ]
