# Generated by Django 5.0.4 on 2024-05-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_order_coupon_order_coupon_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='province',
        ),
    ]
