# Generated by Django 5.0.2 on 2024-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
