# Generated by Django 5.0.2 on 2024-04-18 18:01

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_country_city'),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city',
            field=iranian_cities.fields.ShahrField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr'),
        ),
        migrations.AddField(
            model_name='country',
            name='province',
            field=iranian_cities.fields.OstanField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan'),
        ),
    ]
