# Generated by Django 5.0.2 on 2024-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_reserve_created_at_reserve_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
