# Generated by Django 5.0.2 on 2024-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_reserve_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserved_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
