# Generated by Django 5.0.4 on 2024-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_reserve_reserved_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
