# Generated by Django 5.0.4 on 2024-05-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_userwithcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWithCart',
        ),
    ]
