# Generated by Django 4.2.3 on 2023-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
